import { IconEntry } from "./types";
import {
  StarIcon,
  HeartIcon,
  ShoppingCartIcon,
  MagnifyingGlassIcon,
  UserIcon,
  TrashIcon,
  ChevronDownIcon,
  AdjustmentsHorizontalIcon,
  BarsArrowDownIcon,
  CheckCircleIcon,
  PencilIcon,
  XMarkIcon,
  SunIcon,
  MoonIcon,
  ChatBubbleLeftIcon,
} from "@heroicons/react/24/outline";

export const ICONS = {
  star: { label: "Star", svg: StarIcon },
  heart: { label: "Heart", svg: HeartIcon },
  cart: { label: "Shopping Cart", svg: ShoppingCartIcon },
  search: { label: "Search", svg: MagnifyingGlassIcon },
  account: { label: "Account", svg: UserIcon },
  trash: { label: "Trash", svg: TrashIcon },
  "chevron-down": { label: "Chevron Down", svg: ChevronDownIcon },
  filter: { label: "Filter", svg: AdjustmentsHorizontalIcon },
  sort: { label: "Sort", svg: BarsArrowDownIcon },
  check: { label: "Check", svg: CheckCircleIcon },
  edit: { label: "Edit", svg: PencilIcon },
  close: { label: "Close", svg: XMarkIcon },
  sun: { label: "Sun", svg: SunIcon },
  moon: { label: "Moon", svg: MoonIcon },
  chat: { label: "Chat", svg: ChatBubbleLeftIcon },
} satisfies Record<string, IconEntry>;
